export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const RESET_PWD_SUCCESS = "RESET_PWD_SUCCESS"
export const RESET_PWD_FAIL = "RESET_PWD_FAIL"

export const GET_QUESTIONS_START = 'GET_QUESTIONS_START'
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS'
export const GET_QUESTIONS_FAIL = 'GET_QUESTIONS_FAIL'

export const POST_QUESTIONS_START = 'POST_QUESTIONS_START'
export const POST_QUESTIONS_SUCCESS = 'POST_QUESTIONS_SUCCESS'
export const POST_QUESTIONS_FAIL = 'POST_QUESTIONS_FAIL'

export const GET_CONTESTS_SUCCESS = 'GET_CONTESTS_SUCCESS'
export const GET_CONTESTS_FAIL = 'GET_CONTESTS_FAIL' 

export const POST_CONTESTS_SUCCESS = 'POST_CONTESTS_SUCCESS'
export const POST_CONTESTS_FAIL = 'POST_CONTESTS_FAIL'


export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAIL = "GET_USER_FAIL"

export const POST_USER_SUCCESS = "POST_USER_SUCCESS"
export const POST_USER_FAIL = "POST_USER_FAIL"

export const VERIFY_USER_SUCCESS = "VERIFY_USER_SUCCESS"
export const VERIFY_USER_FAIL = "VERIFY_USER_FAIL"

